version: '3'
services:
  auth:
    build: rebble-auth-py
    volumes:
      - ./rebble-auth-py:/code
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - HOST=0.0.0.0
      - FLASK_APP=auth/__init__.py
    env_file:
      - ./.env
  boot:
    build: rebble-boot
    volumes:
      - ./rebble-boot:/code
    environment:
      - DEBUG=1
      - HOST=0.0.0.0
      - FLASK_APP=boot/__init__.py
    env_file:
      - ./.env
  haproxy:
    build: rebble-dev-fe
    depends_on:
      - auth
      - boot
    ports:
      - 80:80
  db:
    image: "postgres:alpine"