version: '3'
services:
  auth:
    build: ../../apps/auth
    volumes:
      - ../../apps/auth:/code
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - REDIS_URL=redis://redis/0
      - HOST=0.0.0.0
      - FLASK_APP=auth/__init__.py
    env_file:
      - ./.env
  boot:
    build: ../../apps/boot
    volumes:
      - ../../apps/boot:/code
    depends_on:
      - db
    environment:
      - DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - HOST=0.0.0.0
      - FLASK_APP=boot/__init__.py
    env_file:
      - ./.env
  cohorts:
    build: ../../apps/cohorts
    volumes:
      - ../../apps/cohorts:/code
    depends_on:
      - auth
    environment:
      - REBBLE_AUTH=http://auth:5000
      - DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - HOST=0.0.0.0
      - FLASK_APP=cohorts/__init__.py
    env_file:
      - ./.env
  notif-app-icons:
    build: ../../apps/notif-app-icons
    volumes:
      - ../../apps/notif-app-icons:/code
    environment:
      - HOST=0.0.0.0
      - DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - FLASK_APP=icons.py
  lp:
    build: ../../apps/lp
    volumes:
      - ../../apps/lp:/code
    environment:
      - HOST=0.0.0.0
      - DEBUG=1
      - FLASK_APP=languages.py
  weather:
    build: ../../apps/weather
    volumes:
      - ../../apps/weather:/code
    environment:
      - HOST=0.0.0.0
      - DEBUG=1
      - FLASK_APP=weather
    env_file:
      - ./.env
  appstore-api:
    build: ../../apps/appstore-api
    volumes:
      - ../../apps/appstore-api:/code
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - DATABASE_URL=postgres://postgres@db/appstore
      - FLASK_APP=appstore
    env_file:
      - ./.env
  timeline-sync:
    build: ../../apps/timeline-sync
    volumes:
      - ../../apps/timeline-sync:/code
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
      - DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - DATABASE_URL=postgres://postgres@db/timeline_sync
      - FLASK_APP=timeline_sync
      - TZ=UTC
    env_file:
      - ./.env
  haproxy:
    build: ../../dev/infra/haproxy-fe
    depends_on:
      - auth
      - boot
      - cohorts
      - notif-app-icons
      - lp
      - weather
      - appstore-api
      - timeline-sync
    ports:
      - "8086:80"
  db:
    image: "postgres:alpine"
  redis:
    image: "redis:3.2-alpine"
